### ISSUE TITLE
Animations for regular controls

### ISSUE THREAD

**Issue by bast0006** [khang-nd/7.css#11]
Many windows 7 controls natively had animations: buttons, checkboxes, radio buttons had fade-in for their backgrounds on hover. 

There is also an interesting detail--the glass reflections in windows 7 were actually fixed, that is, moving the window did not move where the reflections were on the screen. 

I'm not sure if the second is reasonably implementable in css--it might end up difficult or impossible, but the former is probably doable with a bunch of transition: statements.

**Comment by ZeikJT** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment
Using a fixed value would probably work to emulate the background effect.

**Comment by cyan-2048** [comment]
the glass stripes reflection i have mentioned in #30 with a picture for proof of concept

**Comment by khang-nd** [comment]
Just to point out that the button is not gonna be animated easily due to the `linear-gradient` being used. Though I found that there was a [workaround](https://keithjgrant.com/posts/2017/07/transitioning-gradients/), I really do not want to complicate it too much using these that people might find it difficult to override the styles.
