### ISSUE TITLE
<label> with embedded inputs problematic (should behave like <label for=x>)

### ISSUE THREAD

**Issue by ugumba** [khang-nd/7.css#2]
Thanks for a great looking CSS!
One problem: it requires `<label>` to use `for=""`, and doesn't support embedded inputs.
This then requires us to generate a unique id for each labelled input, which bloats the HTML unnecessarily.

For example:
An input embedded in a `<label>` renders no gap between the label text and the input.
A radio embedded in a `<label>` fails to render the radio at all.

Is that possible to fix?  I'd love to contribute a fix, but my CSS knowledge is sketchy at best.

**Comment by khang-nd** [comment]
Hello, thanks for raising the concern. Because we are limiting the styling to semantic tags as much as possible, it is why we have to follow this pattern for the inputs.

If we were to support `<label><input /></label>`, we had to style all of the labels, which would introduce the collision with other labels that hold no input, and we have no possibility from CSS to select from input to the parent label. One workaround is adding a class to the label, but then it doesn't solve your concern about bloating the HTML.

**Comment by ugumba** [comment]
Thanks for replying.
I've created a radio button component which generates an UUID id and an associated `<label for="">`.
For the other `<label>`s, this is sufficient for now:
` label { display:block; /* fixes padding between label text and child elements */ }
`
