### ISSUE TITLE
Window's border background doesn't get overriden

### ISSUE THREAD

**Issue by lisandro52** [khang-nd/7.css#22]
Hi! I've been using you library to create a couple of React components, but I've noticed that if a parent element has a `background` or `background-color` property set, all the borders of the window use that color instead of the expected gradient.

I've created a simple codesandbox if it helps:

https://codesandbox.io/s/thirsty-wright-rm98t6?file=/index.html

If I remove the `background-color`, the borders re-appear. I think it has to do with the z-index of the `.window::before` but I'm not a style expert haha

**Comment by khang-nd** [comment]
Hello @lisandro52, thanks for pointing that out (the sample codesandbox is really helpful), it is indeed due to the `z-index` on the `window::before` element.

A quick workaround is by specifying `z-index: 0` for `.window` to push the windows above the parent background and reveal the borders. I'm not sure if there's any downside with this approach but afaik, there should be no impact on others.

I will find sometime to make this change and merge into the main branch, for the time being, you can implement this fix in your code. Hope it helps 🙂

**Comment by lisandro52** [comment]
Hey, thanks for the quick answer.

That quick-fix does trick, thank you. I had tried setting `.window::before`'s z-index to 0, but that brings the whole gradient to the front. I would have never tried setting it to `.window`!
